version: "3.3"
services:
  database:
    image: postgres:16-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=Allan
      - POSTGRES_PASSWORD=root
    volumes:
      - pg_data:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
  pg_data: