version: '3'
services:
  #  app:
  #    image: devergente:latest
  #    build:
  #      context: .
  #    container_name: app
  #    depends_on:
  #      - db
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
  #      - SPRING_DATASOURCE_USERNAME=Allan
  #      - SPRING_DATASOURCE_PASSWORD=root
  #      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #      - SPRING_JPA_SHOW_SQL=true
  #      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
  #      - SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS=true
  #      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
  #    ports:
  #      - "8080:8080"
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=Allan
      - POSTGRES_PASSWORD=root
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pg_data:
